name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup NodeJS environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: yarn install
      - name: lint the code
        run: yarn lint

